baseURL = "https://www.yet-another-blog.com"
publishDir = "../docs"
title = "Yet Another Blog"

theme = "puppet"

copyright = "Simon van Bernem"
paginate = 10
languageCode = "en"
defaultContentLanguage = "en"

hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

disqusShortname = "yet-another-blog"

[outputs]
home = ["HTML", "JSON", "RSS"]

# prevent build failures when using Hugo's template _internal/opengraph.html 
[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
[markup.highlight]
noClasses = true
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = false
style = "dracula"

[markup.goldmark.renderer]
unsafe = true


[params]
author = "Simon van Bernem"
keywords = "blog,developer,personal"
googleAnalyticsID = "G-B67BXB63M2"

useFaviconGenerator = true

custom_js = []
custom_css = [] # ["css/custom.css"]  Add your file to assets folder  [assets/css/custom.css]

[params.sidebar]
enable = true
bio = "I'm Simon van Bernem, a software developer from Aachen, who is into all kinds of low-level and game related programming."

[params.social]
rss_enable = true
twitter = "pulp_user"